
# html lang
language: en

# main menu navigation
menu:
  Blog: /
  About: /about
  Archives: /archives

# Social sharing identifiers
social:
  twitter: jbreckmckye

# Enable sidebars
sidebars:
  recent: true
  featured: false
  github: jbreckmckye

# Miscellaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:

# scripts loaded in the end of the body
scripts:
